FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o rest-server ./cmd/rest

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache ca-certificates
EXPOSE 90
COPY --from=builder /app/rest-server .
CMD ["./rest-server"]
