// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: summarize/summarize.proto

package summarize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummarizeUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"` // e.g., "Questions & Answers", "Flowchart & Diagrams"
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`         // e.g., "FREE", "PRO", "PREMIUM"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeUrlRequest) Reset() {
	*x = SummarizeUrlRequest{}
	mi := &file_summarize_summarize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeUrlRequest) ProtoMessage() {}

func (x *SummarizeUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summarize_summarize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeUrlRequest.ProtoReflect.Descriptor instead.
func (*SummarizeUrlRequest) Descriptor() ([]byte, []int) {
	return file_summarize_summarize_proto_rawDescGZIP(), []int{0}
}

func (x *SummarizeUrlRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *SummarizeUrlRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *SummarizeUrlRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SummarizeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"` // e.g., "Questions & Answers", "Flowchart & Diagrams"
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`         // e.g., "FREE", "PRO", "PREMIUM"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeTextRequest) Reset() {
	*x = SummarizeTextRequest{}
	mi := &file_summarize_summarize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeTextRequest) ProtoMessage() {}

func (x *SummarizeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summarize_summarize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeTextRequest.ProtoReflect.Descriptor instead.
func (*SummarizeTextRequest) Descriptor() ([]byte, []int) {
	return file_summarize_summarize_proto_rawDescGZIP(), []int{1}
}

func (x *SummarizeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SummarizeTextRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *SummarizeTextRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SummarizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Questions     string                 `protobuf:"bytes,2,opt,name=questions,proto3" json:"questions,omitempty"`                        // JSON string or empty
	ImageBase64   string                 `protobuf:"bytes,3,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"` // Base64 encoded image or empty
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_summarize_summarize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_summarize_summarize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_summarize_summarize_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeResponse) GetQuestions() string {
	if x != nil {
		return x.Questions
	}
	return ""
}

func (x *SummarizeResponse) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *SummarizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_summarize_summarize_proto protoreflect.FileDescriptor

const file_summarize_summarize_proto_rawDesc = "" +
	"\n" +
	"\x19summarize/summarize.proto\x12\tsummarize\"b\n" +
	"\x13SummarizeUrlRequest\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"Z\n" +
	"\x14SummarizeTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x84\x01\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1c\n" +
	"\tquestions\x18\x02 \x01(\tR\tquestions\x12!\n" +
	"\fimage_base64\x18\x03 \x01(\tR\vimageBase64\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xad\x01\n" +
	"\tSummarize\x12N\n" +
	"\fSummarizeUrl\x12\x1e.summarize.SummarizeUrlRequest\x1a\x1c.summarize.SummarizeResponse\"\x00\x12P\n" +
	"\rSummarizeText\x12\x1f.summarize.SummarizeTextRequest\x1a\x1c.summarize.SummarizeResponse\"\x00B\x16Z\x14/summarize;summarizeb\x06proto3"

var (
	file_summarize_summarize_proto_rawDescOnce sync.Once
	file_summarize_summarize_proto_rawDescData []byte
)

func file_summarize_summarize_proto_rawDescGZIP() []byte {
	file_summarize_summarize_proto_rawDescOnce.Do(func() {
		file_summarize_summarize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_summarize_summarize_proto_rawDesc), len(file_summarize_summarize_proto_rawDesc)))
	})
	return file_summarize_summarize_proto_rawDescData
}

var file_summarize_summarize_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_summarize_summarize_proto_goTypes = []any{
	(*SummarizeUrlRequest)(nil),  // 0: summarize.SummarizeUrlRequest
	(*SummarizeTextRequest)(nil), // 1: summarize.SummarizeTextRequest
	(*SummarizeResponse)(nil),    // 2: summarize.SummarizeResponse
}
var file_summarize_summarize_proto_depIdxs = []int32{
	0, // 0: summarize.Summarize.SummarizeUrl:input_type -> summarize.SummarizeUrlRequest
	1, // 1: summarize.Summarize.SummarizeText:input_type -> summarize.SummarizeTextRequest
	2, // 2: summarize.Summarize.SummarizeUrl:output_type -> summarize.SummarizeResponse
	2, // 3: summarize.Summarize.SummarizeText:output_type -> summarize.SummarizeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_summarize_summarize_proto_init() }
func file_summarize_summarize_proto_init() {
	if File_summarize_summarize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_summarize_summarize_proto_rawDesc), len(file_summarize_summarize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summarize_summarize_proto_goTypes,
		DependencyIndexes: file_summarize_summarize_proto_depIdxs,
		MessageInfos:      file_summarize_summarize_proto_msgTypes,
	}.Build()
	File_summarize_summarize_proto = out.File
	file_summarize_summarize_proto_goTypes = nil
	file_summarize_summarize_proto_depIdxs = nil
}
