// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: summarize/summarize.proto

package summarize

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Summarize_SummarizeUrl_FullMethodName  = "/summarize.Summarize/SummarizeUrl"
	Summarize_SummarizeText_FullMethodName = "/summarize.Summarize/SummarizeText"
)

// SummarizeClient is the client API for Summarize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummarizeClient interface {
	SummarizeUrl(ctx context.Context, in *SummarizeUrlRequest, opts ...grpc.CallOption) (*SummarizeResponse, error)
	SummarizeText(ctx context.Context, in *SummarizeTextRequest, opts ...grpc.CallOption) (*SummarizeResponse, error)
}

type summarizeClient struct {
	cc grpc.ClientConnInterface
}

func NewSummarizeClient(cc grpc.ClientConnInterface) SummarizeClient {
	return &summarizeClient{cc}
}

func (c *summarizeClient) SummarizeUrl(ctx context.Context, in *SummarizeUrlRequest, opts ...grpc.CallOption) (*SummarizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeResponse)
	err := c.cc.Invoke(ctx, Summarize_SummarizeUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summarizeClient) SummarizeText(ctx context.Context, in *SummarizeTextRequest, opts ...grpc.CallOption) (*SummarizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeResponse)
	err := c.cc.Invoke(ctx, Summarize_SummarizeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummarizeServer is the server API for Summarize service.
// All implementations must embed UnimplementedSummarizeServer
// for forward compatibility.
type SummarizeServer interface {
	SummarizeUrl(context.Context, *SummarizeUrlRequest) (*SummarizeResponse, error)
	SummarizeText(context.Context, *SummarizeTextRequest) (*SummarizeResponse, error)
	mustEmbedUnimplementedSummarizeServer()
}

// UnimplementedSummarizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummarizeServer struct{}

func (UnimplementedSummarizeServer) SummarizeUrl(context.Context, *SummarizeUrlRequest) (*SummarizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeUrl not implemented")
}
func (UnimplementedSummarizeServer) SummarizeText(context.Context, *SummarizeTextRequest) (*SummarizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeText not implemented")
}
func (UnimplementedSummarizeServer) mustEmbedUnimplementedSummarizeServer() {}
func (UnimplementedSummarizeServer) testEmbeddedByValue()                   {}

// UnsafeSummarizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummarizeServer will
// result in compilation errors.
type UnsafeSummarizeServer interface {
	mustEmbedUnimplementedSummarizeServer()
}

func RegisterSummarizeServer(s grpc.ServiceRegistrar, srv SummarizeServer) {
	// If the following call panics, it indicates UnimplementedSummarizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Summarize_ServiceDesc, srv)
}

func _Summarize_SummarizeUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizeServer).SummarizeUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summarize_SummarizeUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizeServer).SummarizeUrl(ctx, req.(*SummarizeUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summarize_SummarizeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizeServer).SummarizeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summarize_SummarizeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizeServer).SummarizeText(ctx, req.(*SummarizeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Summarize_ServiceDesc is the grpc.ServiceDesc for Summarize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Summarize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "summarize.Summarize",
	HandlerType: (*SummarizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeUrl",
			Handler:    _Summarize_SummarizeUrl_Handler,
		},
		{
			MethodName: "SummarizeText",
			Handler:    _Summarize_SummarizeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summarize/summarize.proto",
}
